spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/newsapp_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app_schema
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: "none"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8050

logging:
  level:
    root: INFO
