version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newsapp_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
